### ISSUE TITLE
Docker container (request)

### ISSUE THREAD

**Issue by m-liddell** [leekgroup/recount-contributions#3]
I've been trying to follow the instructions for preparing my data after running Rail-RNA and am having problems with the amount of dependencies these additional tools need and getting them to run. Some do not look to be maintained.

Release of a docker container would greatly assist this if it is possible.

**Comment by lcolladotor** [comment]
Unless @nellore has a different opinion, I don't think that we'll be able to handle your request. We are currently working on a new iteration of the project called `recount3`. 

I'll close the issue for now, though @nellore might want to re-open it.

Best,
Leo
